added 04-lection2-02-sceleton
js-tasks-ru/htmlcss-20210513_kabracupa31 pull request #10
Opened 2021-05-23 15:51 UTC by WildeMinze

2021-05-23 15:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-23 21:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-28 11:47 UTC, GSemikozov requested changes

2021-05-28 11:47 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.sceleton-container{
контейнер как обычно унесем из файла блока)

2021-05-28 11:47 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    padding-right: 16px;
тут должен быть внешний отступ

2021-05-28 11:47 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    height: 64px;
чтобы получился круг - нужно еще такую же фиксированную ширину задать, и скруглить углы -  `border-radius: 50%`

2021-05-28 11:47 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.sceleton-item {
и тут я предлагаю переверстать блок чтобы он соответствовал БЭМ подходу)
1. класс блока - .skeleton
2. элемент скелетона хедер - `.skeleton__header`
3. элемент скелетона контент - `.skeleton__content`
4. элемент скелетона аватар - `.skeleton__avatar`
5. элемент скелетона линия - `.skeleton__line`
6. фон определенный в `.sceleton-item-background` - удалим а фон добавим прямо в аватар и линию
7. `.sc-headerItems` -> `.skeleton__header-lines`

2021-05-28 11:47 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-bottom: 8px;
так лучше не делать, отступы зададим конкретным элементам: 
`.skeleton__content-line + .skeleton__content-line { margin-top: 8px; }`
чем хороша такая запись - мы добавим отступ сверху только в случае если у линии будет сосед снизу, и наоборот - если линия будет одна - то и отступ не будет добавляться (избежим лишних отступов).

2021-05-28 11:47 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.sceleton-item {
8. `.sc-header__item` -> `.skeleton__header-line` (если все еще нужен будет этот классс после того как общие стили для линии мы уже определили выше)
9. `.sc-content__item` -> `.skeleton__content-line` (то же самое, если нужен будет)
10. вместо `.sc-header__item-first` и `.sc-header__item-second` -> модификаторы `.skeleton__header-line_short` и `.skeleton__header-line_shorter` (кроме того, при желании можно просто определить модификаторы для самой линии, например - `.skeleton__line_short`, `.skeleton__line_shorter`, `.skeleton__line_medium`, где указать ширину в процентах и использвать их вместо элементов-модификаторов линии у хедера и контента)

2021-05-28 18:17 UTC, WildeMinze commented on 04-lection2/02-skeleton/skeleton.css
> +.sceleton-container{
готово

2021-05-28 18:17 UTC, WildeMinze commented on 04-lection2/02-skeleton/skeleton.css
> +    padding-right: 16px;
готово

2021-05-28 18:17 UTC, WildeMinze commented on 04-lection2/02-skeleton/skeleton.css
> +    height: 64px;
готово

2021-05-28 18:17 UTC, WildeMinze commented on 04-lection2/02-skeleton/skeleton.css
> +.sceleton-item {
готово

2021-05-28 18:18 UTC, WildeMinze commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-bottom: 8px;
готово

2021-05-30 11:39 UTC, GSemikozov approved these changes

2021-05-30 11:39 UTC, merged