add 03-lection3-o3-calendar
js-tasks-ru/htmlcss-20210513_kabracupa31 pull request #12
Opened 2021-05-25 21:36 UTC by WildeMinze

2021-05-25 21:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-28 11:55 UTC, GSemikozov requested changes

2021-05-28 11:55 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    grid-template-rows: repeat(6, 1fr);
rows здесь не обязательно задавать)

2021-05-28 11:55 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__dayCaption{
`.calendar__dayCaption` -> `.calendar__day-caption`

2021-05-28 11:55 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__day-selectedEnds{
`.calendar__day-selectedEnds` -> `.calendar__day_selected-ends`

2021-05-28 11:55 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__day-selected{
`.calendar__day-selected` -> `.calendar__day_selected`

2021-05-29 07:28 UTC, WildeMinze commented on 05-lection3/03-calendar/calendar.css
> +    grid-template-rows: repeat(6, 1fr);
готово

2021-05-29 07:28 UTC, WildeMinze commented on 05-lection3/03-calendar/calendar.css
> +.calendar__dayCaption{
готово

2021-05-29 07:28 UTC, WildeMinze commented on 05-lection3/03-calendar/calendar.css
> +.calendar__day-selectedEnds{
готово

2021-05-29 07:28 UTC, WildeMinze commented on 05-lection3/03-calendar/calendar.css
> +.calendar__day-selected{
готово

2021-05-30 11:40 UTC, GSemikozov submitted a review, later dismissed

2021-05-30 11:41 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2021-05-30 17:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-30 17:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-30 19:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-01 20:26 UTC, GSemikozov approved these changes

2021-06-01 20:26 UTC, merged