05-lection3-01-tooltip
js-tasks-ru/htmlcss-20210513_kabracupa31 pull request #15
Opened 2021-05-31 13:34 UTC by WildeMinze

2021-05-31 13:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-01 11:18 UTC, GSemikozov requested changes

2021-06-01 11:18 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.wrapper{
враппер нужно вынести из блока, например, в html с решением задачи

2021-06-01 11:18 UTC, GSemikozov commented on 05-lection3/01-tooltip/index.html
> +                        <use xlink:href="../../assets/images/sprite.svg#icon-help"/>
работает с live server, все ок?

2021-06-01 11:18 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip__text_visible{
в случае с тултипом мы не используем js чтобы навесить класс-модификатор, здесь мы должны добавиться возможности показать подсказку на ховер на иконку (на занятии мы как раз так и делали)

2021-06-01 11:18 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip__text_visible{
поэтому - этот класс можно удалить. А выше - поправить: `.tooltip:hover .tooltip__text` -> `.tooltip__icon:hover ~ .tooltip__text`

2021-06-01 11:18 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    position: absolute;
иконку не нужно позиционировать абсолютно

2021-06-01 11:18 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    width:24px;
размеры родителю можно не задавать, пусть растягивается по своему внутреннему содержимому (иконка, которая не будет позиционироваться абсолютно)

2021-06-01 18:12 UTC, WildeMinze commented on 05-lection3/01-tooltip/index.html
> +                        <use xlink:href="../../assets/images/sprite.svg#icon-help"/>
да, иконка отображается

2021-06-01 18:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-02 10:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-02 10:56 UTC, WildeMinze commented on 05-lection3/01-tooltip/tooltip.css
> +.wrapper{
надеюсь, правильно поняла

2021-06-02 10:56 UTC, WildeMinze commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip__text_visible{
есть

2021-06-02 10:56 UTC, WildeMinze commented on 05-lection3/01-tooltip/tooltip.css
> +    width:24px;
есть

2021-06-02 10:56 UTC, WildeMinze commented on 05-lection3/01-tooltip/tooltip.css
> +    position: absolute;
есть

2021-06-07 08:42 UTC, GSemikozov approved these changes

2021-06-07 08:42 UTC, merged