add 07-lection5-01-checkbox-02-radio-03-toggler
js-tasks-ru/htmlcss-20210513_kabracupa31 pull request #19
Opened 2021-06-05 20:56 UTC by WildeMinze

2021-06-05 20:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-05 23:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-06 11:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-07 09:02 UTC, GSemikozov requested changes

2021-06-07 09:02 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    /*visibility: hidden;*/ /*тестилась на хроме 90.0.4430.212 не срабатывает событие focused и табуляция с этим свойством*/
верно, можно не использовать, достаточно opacity, absolute и pointer-events

2021-06-07 09:02 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__input:checked ~ .checkbox__state .checkbox__text::before {
в принципе, для добавления текста в контент элемента можно использовать что-то одно: или before, или after, чтобы избежать ненужного усложнения кода

2021-06-07 15:28 UTC, WildeMinze commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__input:checked ~ .checkbox__state .checkbox__text::before {
есть

2021-06-13 21:02 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    /*visibility: hidden;*/ /*тестилась на хроме 90.0.4430.212 не срабатывает событие focused и табуляция с этим свойством*/
закомментированный код можно удалить)

2021-06-13 21:10 UTC, WildeMinze commented on 07-lection5/01-checkbox/checkbox.css
> +    /*visibility: hidden;*/ /*тестилась на хроме 90.0.4430.212 не срабатывает событие focused и табуляция с этим свойством*/
есть

2021-06-16 19:57 UTC, closed without merging