scss + template + histogram.html + dark-theme
js-tasks-ru/htmlcss-20210513_kabracupa31 pull request #22
Opened 2021-06-12 09:03 UTC by WildeMinze

2021-06-12 09:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-12 14:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-12 14:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-12 14:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-12 14:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-12 15:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-12 16:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-12 18:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-13 14:26 UTC, GSemikozov requested changes

2021-06-13 14:26 UTC, GSemikozov commented on 03-lection1/01-button/button.scss
> +.button-list {
все что относится к внешнему оформлению - выносим за пределы блока и оформляем через миксы)

2021-06-13 14:26 UTC, GSemikozov commented on components/page/page.scss
> +    /*padding: 0 15px;*/
а вот для мобилки паддиинги как раз бы пригодились - тогда по всей странице у контента отступ от краев экрана был бы одинаковым

2021-06-13 14:26 UTC, GSemikozov commented on components/theme/theme.scss
> +.theme {
этот компонент я так понимаю будет реализован / доделан в другом ПР?

2021-06-13 14:26 UTC, GSemikozov commented on postcss.config.js
> +    // require('cssnano'),
можно не бояться использовать

2021-06-13 15:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-13 15:36 UTC, WildeMinze commented on components/theme/theme.scss
> +.theme {
он сделан, просто ПР тогглера еще не заапрувлен и отображается по дефолту. А так переключалка работает и тема меняется на страницах.

2021-06-13 16:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-13 16:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-13 16:17 UTC, WildeMinze commented on 03-lection1/01-button/button.scss
> +.button-list {
Из блока кнопок убрала наследие. Но посмотри - я отправила это в микс на card__content на главной странице и, чует мое сердце, что опять не попала с классами и названиями. БЭМ моя беда(

2021-06-13 16:19 UTC, WildeMinze commented on components/page/page.scss
> +    /*padding: 0 15px;*/
есть. Сделала модификатором, чтобы не мучиться с паддингами в хэдере и футере, где тоже используется Page__box

2021-06-13 16:19 UTC, WildeMinze commented on postcss.config.js
> +    // require('cssnano'),
вернула)

2021-06-13 16:25 UTC, WildeMinze commented on components/theme/theme.scss
> +.theme {
стили тогглера я тоже уже заюзала на странице)

2021-06-13 16:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-13 16:41 UTC, GSemikozov commented on components/theme/theme.scss
> +.theme {
<img width="116" alt="Screenshot 2021-06-13 at 19 41 39" src="https://user-images.githubusercontent.com/6191270/121815462-6148b580-cc7f-11eb-89c2-94733d16ee0b.png">
на gh-pages надо бы обновить)

2021-06-13 16:46 UTC, GSemikozov commented on 03-lection1/01-button/button.scss
> +.button-list {
да, не совсем верно)
если buttons-list - это внутренний элемент карточки, тогда класс будет выглядеть так - `.card__buttons-list`, или `.card__actions`
<img width="334" alt="Screenshot 2021-06-13 at 19 45 01" src="https://user-images.githubusercontent.com/6191270/121815587-eaf88300-cc7f-11eb-93bc-5d236b92a663.png">

2021-06-13 16:46 UTC, WildeMinze commented on components/theme/theme.scss
> +.theme {
Ага, именно так и выглядит)  вот этот пр с тогглером https://github.com/js-tasks-ru/htmlcss-20210513_kabracupa31/pull/19 ждет твоего аппрува, поэтому он нигде не подключен, на страничке его еще нет и светится нативный чекбокс

2021-06-13 18:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-13 19:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-13 20:03 UTC, WildeMinze commented on 03-lection1/01-button/button.scss
> +.button-list {
перенесла в класс cards

2021-06-13 21:01 UTC, GSemikozov approved these changes

2021-06-13 21:01 UTC, merged