Added task 03-lection-01-02-accordion
js-tasks-ru/htmlcss-20210513_kabracupa31 pull request #8
Opened 2021-05-19 11:12 UTC by WildeMinze

2021-05-19 11:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-28 11:30 UTC, GSemikozov requested changes

2021-05-28 11:30 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item  .accordion__item_black{
тут и ниже - слишком много специфических модификаторов, лучше упростить. И еще - не стоит использовать вложенные селекторы, только в случае крайней необходимости (когда отображение элемента зависит от состояния родителя, как в нашем случае если [open] - то мы меняем положение стрелки и отступы).

Вместо `.accordion__item_hidden` предлагаю использовать `.accordion__text` (это все-таки не повторяющийся item, а отдельный элемент).
Вместо `.accordion__item_summary` - `.accordion__summary`.

2021-05-28 11:30 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  .accordion-container{
то что не относится к блоку и то что задает лишь какую-то вспомогательную разметку - стоит вынести в стили html-страницы c решением (можно вставить в тег style).

2021-05-28 11:30 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    float: right;
флоаты категорически запрещено использовать))
давай пока вообще удалим стрелку из этого ПР, и добавим её позже, когда будем добавлять svg-спрайт.

2021-05-28 11:30 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    /*  все ломается(*/
ломается именно из-за отступа и приходится использовать отрицательный марджин чтобы подтянуть повыше?
если об этом речь - то если сделаем фиксы выше (уберем .accordion__item у скрытого блока, и зададим ему паддинги отдельно, но при этом верхний будет =0 - тогда проблема уйдет).

2021-05-28 15:23 UTC, WildeMinze commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item  .accordion__item_black{
готово

2021-05-28 15:24 UTC, WildeMinze commented on 03-lection1/02-accordion/accordion.css
> +  .accordion-container{
готово

2021-05-28 15:24 UTC, WildeMinze commented on 03-lection1/02-accordion/accordion.css
> +    float: right;
готово

2021-05-28 15:54 UTC, WildeMinze commented on 03-lection1/02-accordion/accordion.css
> +    /*  все ломается(*/
На макет, вроде, похоже. Отрицательные марджины отслежу, когда спрайт добавляться будет

2021-05-30 11:33 UTC, GSemikozov requested changes

2021-05-30 11:33 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +body{
это должно быть где-то в глобальных стилях или в стилях общего сброса)

2021-05-30 11:33 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__summary_content{
.accordion__summary_content -> .accordion__summary-content

2021-05-30 19:10 UTC, WildeMinze commented on 03-lection1/02-accordion/accordion.css
> +.accordion__summary_content{
готово

2021-05-30 19:10 UTC, WildeMinze commented on 03-lection1/02-accordion/accordion.css
> +body{
готово

2021-06-01 11:05 UTC, GSemikozov approved these changes

2021-06-01 11:05 UTC, merged