added buttons 03-lection1-01-button
js-tasks-ru/htmlcss-20210513_kabracupa31 pull request #9
Opened 2021-05-20 09:06 UTC by WildeMinze

2021-05-20 09:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-23 05:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-23 05:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-23 06:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-23 06:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-23 06:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-28 11:17 UTC, GSemikozov requested changes

2021-05-28 11:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 100%;
высоту лучше зафиксировать в пикселях (ведь если родитель в которого мы добавим кнопку, будет высотой 1000px - то и кнопка растянется на всю эту высоту =)). А ширину - не стоит задавать вовсе - пусть ширина кнопки определяется по внутреннему своему содержимому, а если надо растянуть по родителю - тогда добавим классс-модификатор `.button_full-width { width: 100%; }`

2021-05-28 11:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: default;
на :active не стоит менять курсор - пусть он всегда будет pointer, и только у disabled - default или not-allowed

2021-05-28 11:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button-font{
это можно переместить в саму `.button`

2021-05-28 11:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button:disabled{
тут в дополнение или вместо - disabled лучше через атрибут `.button[disabled]`.
и чтобы запретить пользователю нажимать на такую кнопку - запретим любые события `pointer-events: none`.

2021-05-28 11:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button-primary{
здесь и ниже - модификаторы задаются через `_`

2021-05-28 11:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button-primary{
`.button_primary`

2021-05-28 11:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +/*for display*/
то что важно лишь для отображение в файле решения задачи - можно вынести прямо туда и вставить в тег style.  Ну и если мы следуем БЭМ - то в блоке могут быть стили только самого этого блока и его элементов и модификаторов)

2021-05-28 16:34 UTC, WildeMinze commented on 03-lection1/01-button/button.css
> +    width: 100%;
готово

2021-05-28 16:36 UTC, WildeMinze commented on 03-lection1/01-button/button.css
> +    cursor: default;
готово

2021-05-28 16:36 UTC, WildeMinze commented on 03-lection1/01-button/button.css
> +.button-font{
готово

2021-05-28 16:36 UTC, WildeMinze commented on 03-lection1/01-button/button.css
> +.button:disabled{
готово

2021-05-28 16:36 UTC, WildeMinze commented on 03-lection1/01-button/button.css
> +.button-primary{
готово

2021-05-28 16:36 UTC, WildeMinze commented on 03-lection1/01-button/button.css
> +/*for display*/
готово

2021-05-30 11:36 UTC, GSemikozov requested changes

2021-05-30 11:36 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    color : var(--white);
вот здесь между color и `:` лишний пробел нужно убрать, иначе код будет не валидным)

2021-05-30 11:36 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
кстати, этот тип курсора здесь не нужен, можно удалить (при pointer-events: none по умолчанию будет cursor: default)

2021-05-30 11:36 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
прошу прощения, что повел не верным путем)

2021-05-30 11:36 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +/*for display*/
по-прежнему вижу стили которые касаются внешней разметки внутри стилей блока "кнопка")

2021-05-30 17:17 UTC, WildeMinze commented on 03-lection1/01-button/button.css
> +    color : var(--white);
готово

2021-05-30 17:17 UTC, WildeMinze commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
) готово

2021-05-30 19:04 UTC, GSemikozov approved these changes

2021-05-30 19:05 UTC, merged